/**
 * ⚠️ 这部分接口类型(交易流水 + 计算器)是手写 stub(后端 OpenAPI 自动生成的是嵌套结构,使用不便)
 * 实际 OpenAPI 类型在 paths/operations 中,详细见 docs/api-contract/api-contract.md
 * 完整生成物见 types.ts(下方)
 *
 * 设计原则(frontend-arch §12.5):
 * - Decimal → string(后端 JSON 序列化保留精度)
 * - int / float → number
 * - snake_case → camelCase(由 axios 拦截器自动转换)
 */

export interface HealthResponse {
  status: string;
}

/** LLM Keys 状态(v2.1) */
export interface LlmKeysStatus {
  deepseek: boolean;
  minimax: boolean;
  doubao: boolean;
}

/** LLM Test 响应 */
export interface LlmTestResponse {
  ok: boolean;
  latencyMs: number | null;
  error: string | null;
}

export interface LlmTestRequest {
  provider: 'deepseek' | 'minimax' | 'doubao';
}

export interface LlmKeysUpdate {
  deepseek: string;
  minimax: string;
  doubao: string;
}

/** 交易流水(P2.1 实施) */
export interface Transaction {
  id: number;
  stockCode: string;
  stockName: string | null;
  action: 'buy' | 'sell';
  shares: number;
  price: string;
  tradeDate: string;
  note: string | null;
  score: number | null;
  createdAt: string;
}

export interface TransactionCreate {
  stockCode: string;
  action: 'buy' | 'sell';
  shares: number;
  price: string;
  tradeDate: string;
  stockName?: string;
  note?: string;
}

export interface TransactionListResponse {
  items: Transaction[];
  total: number;
}

/** 持仓(P2.3) */
export interface Position {
  stockCode: string;
  stockName: string | null;
  shares: number;
  avgCost: string;
  totalCost: string;
  realizedPnl: string;
}

export interface PositionListResponse {
  items: Position[];
}

/** 计算器(P3.2) */
export interface CalculatorRequest {
  stockCode: string;
  action: 'buy' | 'sell';
  txShares: number;
  txPrice: string;
}

export interface CalculatorBefore {
  shares: number;
  costPrice: string;
  totalCost: string;
}

export interface CalculatorAfter {
  shares: number;
  costPrice: string | null;
  totalCost: string;
  deltaCost: string | null;
  realizedPnl: string;
}

export interface PnlGridRow {
  pct: number;
  price: string;
  marketValue: string;
  pnl: string;
}

export interface CalculatorResponse {
  input: CalculatorRequest;
  before: CalculatorBefore;
  after: CalculatorAfter;
  pnlGrid: PnlGridRow[];
}

/** 自选股(P2.2) */
export interface WatchlistItem {
  stockCode: string;
  stockName: string | null;
  source: string;
  note: string | null;
  addedAt: string;
}

export interface WatchlistListResponse {
  items: WatchlistItem[];
}

/** 错误响应统一格式 */
export interface ApiError {
  code: string;
  message: string;
  detail?: Record<string, unknown>;
}

/* ============================================================
 * 下方是 openapi-typescript 生成的完整 OpenAPI 类型(嵌套结构)
 * 平时用上方手写接口即可,需要查完整 schema 时用 paths[key]
 * ============================================================
 */

/** This file was auto-generated by openapi-typescript. */
export interface paths {
  // (下面是 18 个端点的完整 OpenAPI schema)
}